/**
 * Local, static catalog of well-known films — the raw source data.
 *
 * Each entry is a compact tuple: [title, year, tags] where `tags` is a
 * space-separated list of genre/tone descriptors. This dense form keeps a
 * ~1,000-film catalog readable and easy to extend. `lib/movies.ts` turns these
 * into `Movie` objects, de-duplicates by title, and exposes the helpers the app
 * uses (lookup + random pairing).
 *
 * Tags are chosen to be useful as creative reference points for "X meets Y"
 * pitches — a mix of genre (sci-fi, noir, western…) and tone (bleak, dreamlike,
 * whimsical, surreal…). They are intentionally lightweight, not exhaustive.
 *
 * This is a curated local catalog only — no external movie API is involved.
 */

export type RawMovie = [title: string, year: number, tags: string];

export const RAW_MOVIES: RawMovie[] = [
  // --- Hollywood Golden Age & classics (1920s–1950s) ---
  ["Metropolis", 1927, "sci-fi silent dystopian expressionist"],
  ["The Passion of Joan of Arc", 1928, "drama silent historical austere"],
  ["City Lights", 1931, "comedy romance silent tender"],
  ["M", 1931, "crime thriller noir tense"],
  ["Dracula", 1931, "horror gothic supernatural classic"],
  ["Frankenstein", 1931, "horror gothic tragic classic"],
  ["King Kong", 1933, "adventure monster spectacle classic"],
  ["It Happened One Night", 1934, "comedy romance screwball charming"],
  ["Modern Times", 1936, "comedy satire silent humane"],
  ["Snow White and the Seven Dwarfs", 1937, "animation fairytale musical wholesome"],
  ["Bringing Up Baby", 1938, "comedy screwball romance frantic"],
  ["The Wizard of Oz", 1939, "fantasy musical adventure whimsical"],
  ["Gone with the Wind", 1939, "drama romance epic historical"],
  ["Stagecoach", 1939, "western adventure ensemble classic"],
  ["The Grapes of Wrath", 1940, "drama social bleak humane"],
  ["Rebecca", 1940, "thriller gothic romance mystery"],
  ["Fantasia", 1940, "animation musical experimental dreamlike"],
  ["Citizen Kane", 1941, "drama mystery epic ambitious"],
  ["The Maltese Falcon", 1941, "noir crime mystery stylish"],
  ["Casablanca", 1942, "romance drama war bittersweet"],
  ["Double Indemnity", 1944, "noir crime thriller cynical"],
  ["Brief Encounter", 1945, "romance drama restrained melancholic"],
  ["Notorious", 1946, "thriller romance espionage suspenseful"],
  ["It's a Wonderful Life", 1946, "drama fantasy heartfelt hopeful"],
  ["The Big Sleep", 1946, "noir crime mystery labyrinthine"],
  ["Out of the Past", 1947, "noir crime romance fatalistic"],
  ["The Treasure of the Sierra Madre", 1948, "adventure drama greed gritty"],
  ["Bicycle Thieves", 1948, "drama neorealist bleak humane"],
  ["The Third Man", 1949, "noir thriller mystery atmospheric"],
  ["Sunset Boulevard", 1950, "noir drama hollywood macabre"],
  ["All About Eve", 1950, "drama theater witty cutting"],
  ["Rashomon", 1950, "drama mystery philosophical inventive"],
  ["A Streetcar Named Desire", 1951, "drama tragedy intense southern"],
  ["Strangers on a Train", 1951, "thriller suspense noir clever"],
  ["The Day the Earth Stood Still", 1951, "sci-fi drama allegory classic"],
  ["Singin' in the Rain", 1952, "musical comedy joyful classic"],
  ["High Noon", 1952, "western drama tense moral"],
  ["Tokyo Story", 1953, "drama family quiet melancholic"],
  ["Roman Holiday", 1953, "romance comedy charming bittersweet"],
  ["Seven Samurai", 1954, "action adventure epic samurai"],
  ["Rear Window", 1954, "thriller mystery suspense voyeuristic"],
  ["On the Waterfront", 1954, "drama crime gritty moral"],
  ["La Strada", 1954, "drama melancholic poetic tender"],
  ["The Night of the Hunter", 1955, "thriller noir gothic nightmarish"],
  ["Rebel Without a Cause", 1955, "drama coming-of-age restless iconic"],
  ["The Searchers", 1956, "western drama epic obsessive"],
  ["Seven Year Itch", 1955, "comedy romance playful satire"],
  ["12 Angry Men", 1957, "drama thriller tense confined"],
  ["The Seventh Seal", 1957, "drama philosophical allegory bleak"],
  ["Wild Strawberries", 1957, "drama reflective melancholic poetic"],
  ["The Bridge on the River Kwai", 1957, "war drama epic moral"],
  ["Witness for the Prosecution", 1957, "thriller mystery courtroom clever"],
  ["Vertigo", 1958, "thriller romance mystery obsessive"],
  ["Touch of Evil", 1958, "noir crime stylish baroque"],
  ["North by Northwest", 1959, "thriller adventure espionage breezy"],
  ["Some Like It Hot", 1959, "comedy crime farce delightful"],
  ["The 400 Blows", 1959, "drama coming-of-age tender melancholic"],
  ["Ben-Hur", 1959, "epic historical drama spectacle"],

  // --- 1960s ---
  ["Psycho", 1960, "horror thriller shocking iconic"],
  ["La Dolce Vita", 1960, "drama satire decadent stylish"],
  ["Breathless", 1960, "crime romance newwave cool"],
  ["The Apartment", 1960, "comedy drama bittersweet humane"],
  ["Spartacus", 1960, "epic historical drama rebellion"],
  ["Peeping Tom", 1960, "horror thriller voyeuristic disturbing"],
  ["Breakfast at Tiffany's", 1961, "romance comedy stylish wistful"],
  ["Yojimbo", 1961, "action samurai wry gritty"],
  ["West Side Story", 1961, "musical romance tragedy vibrant"],
  ["La Jetée", 1962, "sci-fi experimental haunting poetic"],
  ["Lawrence of Arabia", 1962, "epic adventure historical sweeping"],
  ["The Manchurian Candidate", 1962, "thriller political paranoid sharp"],
  ["To Kill a Mockingbird", 1962, "drama social moral tender"],
  ["8½", 1963, "drama surreal reflective inventive"],
  ["The Birds", 1963, "horror thriller eerie apocalyptic"],
  ["The Great Escape", 1963, "war adventure ensemble rousing"],
  ["Dr. Strangelove", 1964, "comedy satire political absurdist"],
  ["A Fistful of Dollars", 1964, "western action gritty iconic"],
  ["My Fair Lady", 1964, "musical romance lavish witty"],
  ["Mary Poppins", 1964, "musical fantasy family whimsical"],
  ["Repulsion", 1965, "horror psychological claustrophobic disturbing"],
  ["The Sound of Music", 1965, "musical drama uplifting family"],
  ["Doctor Zhivago", 1965, "romance epic historical sweeping"],
  ["Persona", 1966, "drama psychological experimental enigmatic"],
  ["The Good, the Bad and the Ugly", 1966, "western epic action iconic"],
  ["Blow-Up", 1966, "mystery drama mod enigmatic"],
  ["Who's Afraid of Virginia Woolf?", 1966, "drama marriage caustic theatrical"],
  ["Bonnie and Clyde", 1967, "crime drama violent stylish"],
  ["The Graduate", 1967, "comedy drama coming-of-age wry"],
  ["Cool Hand Luke", 1967, "drama prison rebellion stoic"],
  ["Le Samouraï", 1967, "noir crime minimalist cool"],
  ["2001: A Space Odyssey", 1968, "sci-fi epic philosophical awe-inspiring"],
  ["Rosemary's Baby", 1968, "horror psychological paranoid dread"],
  ["Once Upon a Time in the West", 1968, "western epic operatic elegiac"],
  ["Night of the Living Dead", 1968, "horror zombie bleak influential"],
  ["Planet of the Apes", 1968, "sci-fi adventure allegory twist"],
  ["The Lion in Winter", 1968, "drama historical sharp theatrical"],
  ["Easy Rider", 1969, "drama road counterculture restless"],
  ["The Wild Bunch", 1969, "western action violent elegiac"],
  ["Butch Cassidy and the Sundance Kid", 1969, "western comedy buddy breezy"],
  ["Midnight Cowboy", 1969, "drama gritty tender urban"],

  // --- 1970s New Hollywood & world cinema ---
  ["MASH", 1970, "comedy war satire irreverent"],
  ["The Conformist", 1970, "drama political stylish chilling"],
  ["A Clockwork Orange", 1971, "sci-fi crime dystopian provocative"],
  ["The French Connection", 1971, "crime thriller gritty kinetic"],
  ["Dirty Harry", 1971, "action crime tough iconic"],
  ["Harold and Maude", 1971, "comedy romance offbeat tender"],
  ["Willy Wonka & the Chocolate Factory", 1971, "fantasy musical whimsical eerie"],
  ["The Last Picture Show", 1971, "drama coming-of-age melancholic"],
  ["Get Carter", 1971, "crime thriller bleak hardboiled"],
  ["The Godfather", 1972, "crime drama epic operatic"],
  ["Solaris", 1972, "sci-fi drama meditative haunting"],
  ["Aguirre, the Wrath of God", 1972, "drama adventure feverish hypnotic"],
  ["Deliverance", 1972, "thriller adventure primal harrowing"],
  ["Cabaret", 1972, "musical drama decadent unsettling"],
  ["The Exorcist", 1973, "horror supernatural dread iconic"],
  ["Mean Streets", 1973, "crime drama gritty kinetic"],
  ["Badlands", 1973, "crime drama lyrical detached"],
  ["Don't Look Now", 1973, "horror thriller grief eerie"],
  ["Enter the Dragon", 1973, "action martial-arts iconic kinetic"],
  ["The Sting", 1973, "crime comedy caper clever"],
  ["American Graffiti", 1973, "comedy drama nostalgic ensemble"],
  ["Chinatown", 1974, "noir mystery drama fatalistic"],
  ["The Godfather Part II", 1974, "crime drama epic tragic"],
  ["The Conversation", 1974, "thriller drama paranoid intimate"],
  ["Young Frankenstein", 1974, "comedy horror parody affectionate"],
  ["The Texas Chain Saw Massacre", 1974, "horror grindhouse primal relentless"],
  ["Blazing Saddles", 1974, "comedy western satire raucous"],
  ["A Woman Under the Influence", 1974, "drama family raw intense"],
  ["Jaws", 1975, "thriller horror adventure primal"],
  ["One Flew Over the Cuckoo's Nest", 1975, "drama rebellion institutional moving"],
  ["Dog Day Afternoon", 1975, "crime drama tense humane"],
  ["Barry Lyndon", 1975, "drama historical painterly detached"],
  ["Monty Python and the Holy Grail", 1975, "comedy fantasy parody absurdist"],
  ["The Rocky Horror Picture Show", 1975, "musical comedy camp cult"],
  ["Picnic at Hanging Rock", 1975, "mystery drama dreamlike eerie"],
  ["Taxi Driver", 1976, "drama crime urban alienated"],
  ["Network", 1976, "drama satire media prophetic"],
  ["Rocky", 1976, "drama sports underdog rousing"],
  ["Carrie", 1976, "horror supernatural tragic high-school"],
  ["The Outlaw Josey Wales", 1976, "western drama elegiac stoic"],
  ["Star Wars", 1977, "sci-fi adventure space mythic"],
  ["Annie Hall", 1977, "comedy romance neurotic witty"],
  ["Close Encounters of the Third Kind", 1977, "sci-fi drama wonder awe"],
  ["Eraserhead", 1977, "horror surreal nightmarish experimental"],
  ["Suspiria", 1977, "horror supernatural lurid stylish"],
  ["Saturday Night Fever", 1977, "drama music disco gritty"],
  ["Halloween", 1978, "horror slasher suspense iconic"],
  ["The Deer Hunter", 1978, "war drama harrowing epic"],
  ["Dawn of the Dead", 1978, "horror zombie satire gory"],
  ["Days of Heaven", 1978, "drama romance lyrical painterly"],
  ["Grease", 1978, "musical romance nostalgic playful"],
  ["Invasion of the Body Snatchers", 1978, "sci-fi horror paranoid creepy"],
  ["Apocalypse Now", 1979, "war drama epic feverish"],
  ["Alien", 1979, "sci-fi horror claustrophobic dread"],
  ["Manhattan", 1979, "comedy romance bittersweet elegant"],
  ["Mad Max", 1979, "action sci-fi dystopian raw"],
  ["Stalker", 1979, "sci-fi drama meditative enigmatic"],
  ["Being There", 1979, "comedy satire gentle wry"],
  ["Nosferatu the Vampyre", 1979, "horror gothic dreamlike mournful"],
  ["Life of Brian", 1979, "comedy satire religious irreverent"],

  // --- 1980s ---
  ["The Shining", 1980, "horror psychological dread iconic"],
  ["Raging Bull", 1980, "drama sports biopic brutal"],
  ["The Empire Strikes Back", 1980, "sci-fi adventure space mythic"],
  ["Airplane!", 1980, "comedy parody zany relentless"],
  ["Ordinary People", 1980, "drama family grief intimate"],
  ["The Elephant Man", 1980, "drama biopic tender melancholic"],
  ["Friday the 13th", 1980, "horror slasher cabin gory"],
  ["The Blues Brothers", 1980, "comedy musical action raucous"],
  ["Raiders of the Lost Ark", 1981, "adventure action pulp thrilling"],
  ["An American Werewolf in London", 1981, "horror comedy transformative gory"],
  ["The Evil Dead", 1981, "horror cabin gory cult"],
  ["Das Boot", 1981, "war drama claustrophobic tense"],
  ["Blade Runner", 1982, "sci-fi noir melancholic atmospheric"],
  ["E.T. the Extra-Terrestrial", 1982, "sci-fi family wonder heartfelt"],
  ["The Thing", 1982, "horror sci-fi paranoid claustrophobic"],
  ["Fanny and Alexander", 1982, "drama family epic nostalgic"],
  ["Poltergeist", 1982, "horror supernatural suburban dread"],
  ["First Blood", 1982, "action drama survival gritty"],
  ["Tootsie", 1982, "comedy romance sharp humane"],
  ["Fitzcarraldo", 1982, "drama adventure obsessive epic"],
  ["Scarface", 1983, "crime drama excess operatic"],
  ["The King of Comedy", 1983, "comedy drama uncomfortable satire"],
  ["Videodrome", 1983, "horror sci-fi body surreal"],
  ["A Christmas Story", 1983, "comedy family nostalgic warm"],
  ["Star Wars: Return of the Jedi", 1983, "sci-fi adventure space mythic"],
  ["The Terminator", 1984, "sci-fi action relentless dystopian"],
  ["This Is Spinal Tap", 1984, "comedy mockumentary music deadpan"],
  ["Once Upon a Time in America", 1984, "crime drama epic elegiac"],
  ["Paris, Texas", 1984, "drama road melancholic poetic"],
  ["Ghostbusters", 1984, "comedy fantasy supernatural playful"],
  ["Amadeus", 1984, "drama biopic music lavish"],
  ["A Nightmare on Elm Street", 1984, "horror supernatural surreal slasher"],
  ["Gremlins", 1984, "horror comedy creature mischievous"],
  ["The Karate Kid", 1984, "drama sports underdog heartfelt"],
  ["Stranger Than Paradise", 1984, "comedy drama deadpan minimalist"],
  ["Back to the Future", 1985, "sci-fi comedy adventure inventive"],
  ["Brazil", 1985, "sci-fi comedy dystopian surreal"],
  ["Ran", 1985, "drama epic tragedy samurai"],
  ["The Breakfast Club", 1985, "drama comedy coming-of-age earnest"],
  ["Come and See", 1985, "war drama harrowing nightmarish"],
  ["Out of Africa", 1985, "romance drama epic sweeping"],
  ["The Goonies", 1985, "adventure family comedy spirited"],
  ["Blood Simple", 1985, "noir crime thriller taut"],
  ["Aliens", 1986, "sci-fi action horror relentless"],
  ["Blue Velvet", 1986, "mystery thriller surreal disturbing"],
  ["Stand by Me", 1986, "drama coming-of-age nostalgic tender"],
  ["Ferris Bueller's Day Off", 1986, "comedy teen playful breezy"],
  ["Hannah and Her Sisters", 1986, "comedy drama ensemble bittersweet"],
  ["The Fly", 1986, "horror sci-fi body tragic"],
  ["Platoon", 1986, "war drama harrowing visceral"],
  ["Top Gun", 1986, "action drama slick rousing"],
  ["Manhunter", 1986, "thriller crime stylish chilling"],
  ["Labyrinth", 1986, "fantasy musical adventure whimsical"],
  ["Wings of Desire", 1987, "drama fantasy poetic meditative"],
  ["Full Metal Jacket", 1987, "war drama bleak satirical"],
  ["The Princess Bride", 1987, "fantasy romance comedy charming"],
  ["Predator", 1987, "action sci-fi survival relentless"],
  ["RoboCop", 1987, "sci-fi action satire violent"],
  ["Raising Arizona", 1987, "comedy crime zany warm"],
  ["Wall Street", 1987, "drama greed sharp glossy"],
  ["The Untouchables", 1987, "crime drama stylish operatic"],
  ["Evil Dead II", 1987, "horror comedy gory frantic"],
  ["Withnail & I", 1987, "comedy drama melancholic witty"],
  ["Die Hard", 1988, "action thriller confined relentless"],
  ["My Neighbor Totoro", 1988, "animation family gentle whimsical"],
  ["Grave of the Fireflies", 1988, "animation war drama devastating"],
  ["Akira", 1988, "animation sci-fi dystopian explosive"],
  ["Cinema Paradiso", 1988, "drama nostalgic tender bittersweet"],
  ["Who Framed Roger Rabbit", 1988, "comedy animation noir inventive"],
  ["The Last Temptation of Christ", 1988, "drama religious provocative searching"],
  ["Dead Ringers", 1988, "thriller psychological body unsettling"],
  ["Beetlejuice", 1988, "comedy fantasy macabre playful"],
  ["Rain Man", 1988, "drama road heartfelt humane"],
  ["Do the Right Thing", 1989, "drama social vibrant urgent"],
  ["Field of Dreams", 1989, "drama fantasy sports wistful"],
  ["When Harry Met Sally", 1989, "comedy romance witty warm"],
  ["Dead Poets Society", 1989, "drama coming-of-age inspirational earnest"],
  ["Batman", 1989, "action superhero gothic stylish"],
  ["Say Anything", 1989, "romance comedy teen earnest"],
  ["Crimes and Misdemeanors", 1989, "drama comedy moral philosophical"],
  ["Glory", 1989, "war drama historical stirring"],
  ["The Cook, the Thief, His Wife & Her Lover", 1989, "drama crime lurid theatrical"],

  // --- 1990s ---
  ["Goodfellas", 1990, "crime drama kinetic epic"],
  ["Total Recall", 1990, "sci-fi action twist explosive"],
  ["Edward Scissorhands", 1990, "fantasy romance melancholic whimsical"],
  ["Home Alone", 1990, "comedy family festive playful"],
  ["Misery", 1990, "thriller horror confined tense"],
  ["Miller's Crossing", 1990, "crime noir stylish labyrinthine"],
  ["The Silence of the Lambs", 1991, "thriller horror crime chilling"],
  ["Terminator 2: Judgment Day", 1991, "sci-fi action relentless epic"],
  ["Thelma & Louise", 1991, "drama road rebellious liberating"],
  ["Boyz n the Hood", 1991, "drama social urgent humane"],
  ["Beauty and the Beast", 1991, "animation musical romance enchanting"],
  ["My Own Private Idaho", 1991, "drama road dreamy melancholic"],
  ["Barton Fink", 1991, "drama surreal noir uneasy"],
  ["JFK", 1991, "drama political paranoid sprawling"],
  ["Unforgiven", 1992, "western drama elegiac somber"],
  ["Reservoir Dogs", 1992, "crime thriller talky brutal"],
  ["Aladdin", 1992, "animation musical adventure exuberant"],
  ["The Player", 1992, "comedy satire hollywood sly"],
  ["Bram Stoker's Dracula", 1992, "horror romance gothic lush"],
  ["A Few Good Men", 1992, "drama courtroom tense sharp"],
  ["Glengarry Glen Ross", 1992, "drama ensemble caustic intense"],
  ["Schindler's List", 1993, "drama war historical devastating"],
  ["Jurassic Park", 1993, "adventure sci-fi wonder thrilling"],
  ["Groundhog Day", 1993, "comedy fantasy romance philosophical"],
  ["The Nightmare Before Christmas", 1993, "animation musical macabre whimsical"],
  ["Dazed and Confused", 1993, "comedy coming-of-age nostalgic mellow"],
  ["Carlito's Way", 1993, "crime drama tragic operatic"],
  ["Short Cuts", 1993, "drama ensemble interwoven melancholic"],
  ["The Piano", 1993, "drama romance period intense"],
  ["Pulp Fiction", 1994, "crime drama nonlinear stylish"],
  ["The Shawshank Redemption", 1994, "drama prison hopeful moving"],
  ["Forrest Gump", 1994, "drama comedy sweeping sentimental"],
  ["The Lion King", 1994, "animation musical epic emotional"],
  ["Léon: The Professional", 1994, "action crime tender stylish"],
  ["Chungking Express", 1994, "romance drama dreamy kinetic"],
  ["Ed Wood", 1994, "comedy biopic affectionate offbeat"],
  ["Three Colors: Red", 1994, "drama romance contemplative luminous"],
  ["Natural Born Killers", 1994, "crime satire frenzied provocative"],
  ["Clerks", 1994, "comedy indie talky deadpan"],
  ["Quiz Show", 1994, "drama historical moral sharp"],
  ["Heat", 1995, "crime drama epic methodical"],
  ["Se7en", 1995, "thriller crime bleak grim"],
  ["Toy Story", 1995, "animation family adventure heartfelt"],
  ["The Usual Suspects", 1995, "crime thriller twist clever"],
  ["Casino", 1995, "crime drama epic excess"],
  ["Before Sunrise", 1995, "romance drama talky tender"],
  ["Twelve Monkeys", 1995, "sci-fi thriller dystopian disorienting"],
  ["La Haine", 1995, "drama social urgent kinetic"],
  ["Braveheart", 1995, "epic war historical rousing"],
  ["Babe", 1995, "family comedy gentle charming"],
  ["Dead Man", 1995, "western drama surreal meditative"],
  ["Fargo", 1996, "crime comedy dark wry"],
  ["Trainspotting", 1996, "drama comedy frenetic gritty"],
  ["Breaking the Waves", 1996, "drama tragic raw spiritual"],
  ["Scream", 1996, "horror slasher meta playful"],
  ["Independence Day", 1996, "sci-fi action disaster rousing"],
  ["The English Patient", 1996, "romance drama epic sweeping"],
  ["Bottle Rocket", 1996, "comedy crime quirky gentle"],
  ["Mars Attacks!", 1996, "comedy sci-fi satire campy"],
  ["Titanic", 1997, "romance drama epic sweeping"],
  ["L.A. Confidential", 1997, "noir crime stylish twisty"],
  ["Boogie Nights", 1997, "drama ensemble sprawling nostalgic"],
  ["Princess Mononoke", 1997, "animation fantasy epic environmental"],
  ["Good Will Hunting", 1997, "drama coming-of-age heartfelt earnest"],
  ["Jackie Brown", 1997, "crime drama cool laidback"],
  ["The Fifth Element", 1997, "sci-fi action vibrant playful"],
  ["Lost Highway", 1997, "thriller surreal noir nightmarish"],
  ["Gattaca", 1997, "sci-fi drama dystopian sleek"],
  ["Funny Games", 1997, "thriller horror provocative cold"],
  ["The Big Lebowski", 1998, "comedy crime shaggy cult"],
  ["Saving Private Ryan", 1998, "war drama visceral epic"],
  ["The Truman Show", 1998, "drama comedy satire prophetic"],
  ["Rushmore", 1998, "comedy drama quirky bittersweet"],
  ["Run Lola Run", 1998, "thriller kinetic experimental propulsive"],
  ["The Thin Red Line", 1998, "war drama meditative lyrical"],
  ["Ringu", 1998, "horror supernatural eerie dread"],
  ["Pi", 1998, "thriller psychological paranoid grainy"],
  ["The Big One", 1997, "documentary satire pointed wry"],
  ["Dark City", 1998, "sci-fi noir surreal atmospheric"],
  ["The Matrix", 1999, "sci-fi action philosophical stylish"],
  ["Fight Club", 1999, "drama thriller subversive frenetic"],
  ["Magnolia", 1999, "drama ensemble sprawling emotional"],
  ["Being John Malkovich", 1999, "comedy surreal inventive offbeat"],
  ["The Sixth Sense", 1999, "thriller supernatural twist somber"],
  ["Eyes Wide Shut", 1999, "drama mystery dreamlike unsettling"],
  ["American Beauty", 1999, "drama satire suburban melancholic"],
  ["The Iron Giant", 1999, "animation sci-fi family heartfelt"],
  ["Office Space", 1999, "comedy satire workplace deadpan"],
  ["Election", 1999, "comedy satire sharp dark"],
  ["The Blair Witch Project", 1999, "horror found-footage dread minimalist"],
  ["All About My Mother", 1999, "drama melodrama vibrant compassionate"],
  ["Three Kings", 1999, "war action satire kinetic"],
  ["Audition", 1999, "horror thriller slow-burn disturbing"],

  // --- 2000s ---
  ["In the Mood for Love", 2000, "romance drama dreamy melancholic"],
  ["Requiem for a Dream", 2000, "drama addiction harrowing relentless"],
  ["Memento", 2000, "thriller mystery nonlinear ingenious"],
  ["Gladiator", 2000, "epic action historical rousing"],
  ["Crouching Tiger, Hidden Dragon", 2000, "action romance wuxia lyrical"],
  ["Almost Famous", 2000, "drama music nostalgic warm"],
  ["O Brother, Where Art Thou?", 2000, "comedy adventure musical whimsical"],
  ["Yi Yi", 2000, "drama family contemplative tender"],
  ["Battle Royale", 2000, "thriller action dystopian brutal"],
  ["Amores Perros", 2000, "drama interwoven gritty visceral"],
  ["Snatch", 2000, "crime comedy frenetic stylish"],
  ["Amélie", 2001, "romance comedy whimsical charming"],
  ["Mulholland Drive", 2001, "thriller mystery surreal dreamlike"],
  ["The Lord of the Rings: The Fellowship of the Ring", 2001, "fantasy adventure epic mythic"],
  ["Spirited Away", 2001, "animation fantasy enchanting dreamlike"],
  ["Donnie Darko", 2001, "sci-fi drama eerie cult"],
  ["A.I. Artificial Intelligence", 2001, "sci-fi drama melancholic ambitious"],
  ["Monsters, Inc.", 2001, "animation family comedy heartfelt"],
  ["Y Tu Mamá También", 2001, "drama road sensual bittersweet"],
  ["The Royal Tenenbaums", 2001, "comedy drama deadpan melancholic"],
  ["Training Day", 2001, "crime thriller gritty intense"],
  ["The Others", 2001, "horror gothic atmospheric twist"],
  ["No Man's Land", 2001, "war satire bleak biting"],
  ["City of God", 2002, "crime drama kinetic sprawling"],
  ["Spirited Away", 2002, "animation fantasy enchanting dreamlike"],
  ["The Pianist", 2002, "war drama survival devastating"],
  ["Adaptation", 2002, "comedy drama meta inventive"],
  ["Punch-Drunk Love", 2002, "romance comedy offbeat tender"],
  ["Russian Ark", 2002, "drama historical experimental hypnotic"],
  ["Talk to Her", 2002, "drama romance tender unsettling"],
  ["Minority Report", 2002, "sci-fi thriller sleek propulsive"],
  ["28 Days Later", 2002, "horror sci-fi apocalyptic visceral"],
  ["The Lord of the Rings: The Two Towers", 2002, "fantasy adventure epic mythic"],
  ["Catch Me If You Can", 2002, "crime comedy breezy stylish"],
  ["Bowling for Columbine", 2002, "documentary satire pointed provocative"],
  ["Oldboy", 2003, "thriller crime violent operatic"],
  ["Lost in Translation", 2003, "drama romance wistful intimate"],
  ["Finding Nemo", 2003, "animation family adventure heartfelt"],
  ["Kill Bill: Vol. 1", 2003, "action revenge stylish kinetic"],
  ["The Lord of the Rings: The Return of the King", 2003, "fantasy adventure epic mythic"],
  ["Big Fish", 2003, "fantasy drama whimsical bittersweet"],
  ["Memories of Murder", 2003, "crime drama bleak masterful"],
  ["Mystic River", 2003, "drama crime somber tragic"],
  ["School of Rock", 2003, "comedy music joyful warm"],
  ["Spring, Summer, Fall, Winter... and Spring", 2003, "drama meditative serene poetic"],
  ["Eternal Sunshine of the Spotless Mind", 2004, "romance sci-fi melancholic inventive"],
  ["The Incredibles", 2004, "animation action family witty"],
  ["Before Sunset", 2004, "romance drama talky tender"],
  ["Shaun of the Dead", 2004, "comedy horror zombie clever"],
  ["Hotel Rwanda", 2004, "drama war historical harrowing"],
  ["Sideways", 2004, "comedy drama wry melancholic"],
  ["House of Flying Daggers", 2004, "action romance wuxia lush"],
  ["Collateral", 2004, "thriller crime nocturnal sleek"],
  ["Kung Fu Hustle", 2004, "comedy action martial-arts cartoonish"],
  ["The Aviator", 2004, "drama biopic lavish epic"],
  ["A Very Long Engagement", 2004, "romance war drama lush"],
  ["Downfall", 2004, "war drama historical claustrophobic"],
  ["A History of Violence", 2005, "thriller crime tense restrained"],
  ["Brokeback Mountain", 2005, "romance drama aching tender"],
  ["Pride & Prejudice", 2005, "romance period drama luminous"],
  ["Batman Begins", 2005, "action superhero gritty grounded"],
  ["Caché", 2005, "thriller drama unsettling cerebral"],
  ["The New World", 2005, "drama romance lyrical meditative"],
  ["Good Night, and Good Luck", 2005, "drama historical taut principled"],
  ["Munich", 2005, "thriller drama moral tense"],
  ["Howl's Moving Castle", 2004, "animation fantasy whimsical enchanting"],
  ["Pan's Labyrinth", 2006, "fantasy drama dark haunting"],
  ["Children of Men", 2006, "sci-fi drama dystopian visceral"],
  ["The Departed", 2006, "crime thriller twisty propulsive"],
  ["The Prestige", 2006, "thriller mystery obsessive twist"],
  ["The Lives of Others", 2006, "drama political tense humane"],
  ["Little Miss Sunshine", 2006, "comedy drama warm quirky"],
  ["Apocalypto", 2006, "action adventure visceral relentless"],
  ["The Fountain", 2006, "sci-fi romance metaphysical lush"],
  ["Casino Royale", 2006, "action thriller sleek gritty"],
  ["Volver", 2006, "drama comedy vibrant warm"],
  ["Inland Empire", 2006, "thriller surreal nightmarish experimental"],
  ["No Country for Old Men", 2007, "thriller crime bleak fatalistic"],
  ["There Will Be Blood", 2007, "drama epic obsessive austere"],
  ["Ratatouille", 2007, "animation family comedy heartfelt"],
  ["Zodiac", 2007, "thriller crime procedural obsessive"],
  ["No Country for Old Men", 2007, "thriller crime bleak fatalistic"],
  ["Hot Fuzz", 2007, "comedy action parody clever"],
  ["The Diving Bell and the Butterfly", 2007, "drama biopic poetic moving"],
  ["Once", 2007, "romance music intimate tender"],
  ["4 Months, 3 Weeks and 2 Days", 2007, "drama tense harrowing austere"],
  ["Into the Wild", 2007, "drama adventure searching bittersweet"],
  ["Atonement", 2007, "romance drama epic tragic"],
  ["Persepolis", 2007, "animation drama coming-of-age witty"],
  ["The Assassination of Jesse James by the Coward Robert Ford", 2007, "western drama elegiac lyrical"],
  ["Eastern Promises", 2007, "crime thriller cold visceral"],
  ["The Dark Knight", 2008, "action superhero crime epic"],
  ["WALL-E", 2008, "animation sci-fi tender wondrous"],
  ["Let the Right One In", 2008, "horror romance tender eerie"],
  ["Slumdog Millionaire", 2008, "drama romance kinetic uplifting"],
  ["In Bruges", 2008, "comedy crime dark melancholic"],
  ["Gran Torino", 2008, "drama redemption gruff moving"],
  ["Synecdoche, New York", 2008, "drama surreal ambitious melancholic"],
  ["The Wrestler", 2008, "drama sports raw poignant"],
  ["Waltz with Bashir", 2008, "animation documentary war haunting"],
  ["Hunger", 2008, "drama political austere visceral"],
  ["Man on Wire", 2008, "documentary suspense exhilarating poetic"],
  ["Up", 2009, "animation adventure heartfelt poignant"],
  ["Inglourious Basterds", 2009, "war drama revenge stylish"],
  ["A Serious Man", 2009, "comedy drama existential wry"],
  ["District 9", 2009, "sci-fi action allegory gritty"],
  ["Avatar", 2009, "sci-fi adventure spectacle immersive"],
  ["Fantastic Mr. Fox", 2009, "animation comedy whimsical wry"],
  ["The White Ribbon", 2009, "drama mystery austere unsettling"],
  ["A Prophet", 2009, "crime drama immersive gritty"],
  ["Moon", 2009, "sci-fi drama lonely contemplative"],
  ["The Hurt Locker", 2009, "war thriller tense visceral"],
  ["Antichrist", 2009, "horror drama provocative harrowing"],
  ["Coraline", 2009, "animation fantasy macabre whimsical"],

  // --- 2010s ---
  ["Inception", 2010, "sci-fi thriller cerebral propulsive"],
  ["The Social Network", 2010, "drama biopic sharp propulsive"],
  ["Black Swan", 2010, "thriller psychological obsessive lurid"],
  ["Toy Story 3", 2010, "animation family adventure poignant"],
  ["Shutter Island", 2010, "thriller mystery gothic twist"],
  ["Scott Pilgrim vs. the World", 2010, "comedy action romance kinetic"],
  ["True Grit", 2010, "western drama wry rugged"],
  ["Blue Valentine", 2010, "romance drama raw aching"],
  ["Animal Kingdom", 2010, "crime drama tense menacing"],
  ["Enter the Void", 2010, "drama experimental psychedelic immersive"],
  ["The King's Speech", 2010, "drama historical warm uplifting"],
  ["Drive", 2011, "crime thriller stylish moody"],
  ["The Tree of Life", 2011, "drama experimental cosmic poetic"],
  ["Melancholia", 2011, "drama sci-fi apocalyptic somber"],
  ["A Separation", 2011, "drama tense moral humane"],
  ["Midnight in Paris", 2011, "comedy romance whimsical nostalgic"],
  ["Hugo", 2011, "adventure family wondrous nostalgic"],
  ["Take Shelter", 2011, "drama thriller apocalyptic anxious"],
  ["Attack the Block", 2011, "sci-fi comedy action scrappy"],
  ["Tinker Tailor Soldier Spy", 2011, "thriller espionage cerebral austere"],
  ["We Need to Talk About Kevin", 2011, "drama thriller chilling fractured"],
  ["The Artist", 2011, "drama comedy silent charming"],
  ["Moonrise Kingdom", 2012, "comedy romance whimsical tender"],
  ["The Master", 2012, "drama period enigmatic intense"],
  ["Django Unchained", 2012, "western action revenge stylish"],
  ["Holy Motors", 2012, "drama surreal experimental dreamlike"],
  ["The Cabin in the Woods", 2012, "horror comedy meta inventive"],
  ["Beasts of the Southern Wild", 2012, "drama fantasy lyrical raw"],
  ["Amour", 2012, "drama romance austere devastating"],
  ["Looper", 2012, "sci-fi thriller inventive gritty"],
  ["Zero Dark Thirty", 2012, "thriller drama procedural tense"],
  ["The Hunt", 2012, "drama tense harrowing humane"],
  ["Cloud Atlas", 2012, "sci-fi drama sprawling ambitious"],
  ["Her", 2013, "sci-fi romance tender melancholic"],
  ["12 Years a Slave", 2013, "drama historical harrowing unflinching"],
  ["Gravity", 2013, "sci-fi thriller immersive tense"],
  ["The Wolf of Wall Street", 2013, "crime comedy excess frenetic"],
  ["Inside Llewyn Davis", 2013, "drama music melancholic wry"],
  ["Spring Breakers", 2013, "drama crime hypnotic lurid"],
  ["Under the Skin", 2013, "sci-fi horror eerie hypnotic"],
  ["Frances Ha", 2013, "comedy drama buoyant bittersweet"],
  ["The Grand Budapest Hotel", 2014, "comedy adventure whimsical melancholic"],
  ["Boyhood", 2014, "drama coming-of-age intimate sprawling"],
  ["Whiplash", 2014, "drama music intense propulsive"],
  ["Birdman", 2014, "drama comedy theatrical kinetic"],
  ["Nightcrawler", 2014, "thriller crime nocturnal unsettling"],
  ["The Babadook", 2014, "horror drama grief dread"],
  ["Ex Machina", 2014, "sci-fi thriller cerebral sleek"],
  ["Snowpiercer", 2014, "sci-fi action dystopian allegorical"],
  ["Mommy", 2014, "drama family raw vibrant"],
  ["A Most Violent Year", 2014, "crime drama restrained tense"],
  ["Force Majeure", 2014, "drama comedy uncomfortable sharp"],
  ["Selma", 2014, "drama historical stirring principled"],
  ["Mad Max: Fury Road", 2015, "action sci-fi relentless visceral"],
  ["The Witch", 2015, "horror period dread austere"],
  ["Inside Out", 2015, "animation family inventive poignant"],
  ["Carol", 2015, "romance drama tender luminous"],
  ["Sicario", 2015, "thriller crime tense bleak"],
  ["Anomalisa", 2015, "animation drama melancholic intimate"],
  ["Room", 2015, "drama thriller intimate harrowing"],
  ["The Lobster", 2015, "comedy drama absurdist deadpan"],
  ["The Revenant", 2015, "adventure drama brutal immersive"],
  ["Son of Saul", 2015, "war drama harrowing immersive"],
  ["It Follows", 2015, "horror supernatural dread atmospheric"],
  ["Spotlight", 2015, "drama procedural restrained urgent"],
  ["Arrival", 2016, "sci-fi drama cerebral moving"],
  ["Moonlight", 2016, "drama coming-of-age tender lyrical"],
  ["La La Land", 2016, "musical romance bittersweet vibrant"],
  ["The Handmaiden", 2016, "thriller romance lush twisty"],
  ["Manchester by the Sea", 2016, "drama grief restrained devastating"],
  ["Toni Erdmann", 2016, "comedy drama absurd poignant"],
  ["Hell or High Water", 2016, "crime western modern tense"],
  ["The Witch", 2016, "horror period dread austere"],
  ["Paterson", 2016, "drama poetic gentle observant"],
  ["Your Name", 2016, "animation romance sci-fi luminous"],
  ["The Nice Guys", 2016, "comedy crime breezy stylish"],
  ["American Honey", 2016, "drama road sprawling raw"],
  ["Get Out", 2017, "horror thriller satire sharp"],
  ["Lady Bird", 2017, "comedy coming-of-age warm wry"],
  ["Call Me by Your Name", 2017, "romance drama sensual aching"],
  ["Blade Runner 2049", 2017, "sci-fi noir melancholic atmospheric"],
  ["Dunkirk", 2017, "war thriller immersive tense"],
  ["The Florida Project", 2017, "drama vibrant tender bittersweet"],
  ["Phantom Thread", 2017, "drama romance obsessive elegant"],
  ["A Ghost Story", 2017, "drama fantasy meditative melancholic"],
  ["The Shape of Water", 2017, "fantasy romance lush whimsical"],
  ["Good Time", 2017, "thriller crime frenetic gritty"],
  ["Coco", 2017, "animation family musical heartfelt"],
  ["Logan", 2017, "action drama elegiac gritty"],
  ["mother!", 2017, "thriller horror allegorical feverish"],
  ["Hereditary", 2018, "horror drama dread harrowing"],
  ["Roma", 2018, "drama intimate lyrical sweeping"],
  ["Spider-Man: Into the Spider-Verse", 2018, "animation action vibrant inventive"],
  ["Burning", 2018, "thriller drama slow-burn enigmatic"],
  ["Annihilation", 2018, "sci-fi horror cerebral surreal"],
  ["The Favourite", 2018, "comedy drama period acerbic"],
  ["First Reformed", 2018, "drama austere searching intense"],
  ["Shoplifters", 2018, "drama family tender melancholic"],
  ["Eighth Grade", 2018, "comedy drama tender awkward"],
  ["Mandy", 2018, "horror action psychedelic vengeful"],
  ["Cold War", 2018, "romance drama austere sweeping"],
  ["You Were Never Really Here", 2018, "thriller crime visceral fractured"],
  ["Parasite", 2019, "thriller drama satire sharp"],
  ["Marriage Story", 2019, "drama relationship raw intimate"],
  ["Once Upon a Time in Hollywood", 2019, "drama comedy nostalgic leisurely"],
  ["Midsommar", 2019, "horror drama dread lurid"],
  ["The Lighthouse", 2019, "horror drama hallucinatory austere"],
  ["Uncut Gems", 2019, "thriller drama frenetic anxious"],
  ["Knives Out", 2019, "mystery comedy clever twisty"],
  ["Portrait of a Lady on Fire", 2019, "romance drama luminous restrained"],
  ["1917", 2019, "war thriller immersive relentless"],
  ["Jojo Rabbit", 2019, "comedy drama satire tender"],
  ["The Irishman", 2019, "crime drama epic elegiac"],
  ["Pain and Glory", 2019, "drama reflective tender vibrant"],
  ["The Farewell", 2019, "drama comedy tender bittersweet"],
  ["Ad Astra", 2019, "sci-fi drama meditative lonely"],

  // --- 2020s ---
  ["Nomadland", 2020, "drama road meditative tender"],
  ["Soul", 2020, "animation drama philosophical heartfelt"],
  ["Sound of Metal", 2020, "drama intimate immersive moving"],
  ["Promising Young Woman", 2020, "thriller drama satire sharp"],
  ["Minari", 2020, "drama family tender warm"],
  ["The Father", 2020, "drama disorienting devastating intimate"],
  ["First Cow", 2020, "drama western gentle tender"],
  ["Another Round", 2020, "drama comedy bittersweet exuberant"],
  ["Tenet", 2020, "sci-fi thriller cerebral propulsive"],
  ["Possessor", 2020, "sci-fi horror visceral unsettling"],
  ["Dune", 2021, "sci-fi epic adventure immersive"],
  ["The Power of the Dog", 2021, "western drama simmering austere"],
  ["Drive My Car", 2021, "drama contemplative tender quiet"],
  ["The Green Knight", 2021, "fantasy adventure mythic dreamlike"],
  ["Pig", 2021, "drama melancholic understated tender"],
  ["Titane", 2021, "horror drama provocative visceral"],
  ["The Worst Person in the World", 2021, "drama romance buoyant bittersweet"],
  ["Spencer", 2021, "drama biopic haunting claustrophobic"],
  ["The French Dispatch", 2021, "comedy anthology whimsical intricate"],
  ["Licorice Pizza", 2021, "comedy romance nostalgic loose"],
  ["Everything Everywhere All at Once", 2022, "sci-fi action absurd heartfelt"],
  ["The Banshees of Inisherin", 2022, "drama comedy melancholic bleak"],
  ["Tár", 2022, "drama character-study austere unsettling"],
  ["Aftersun", 2022, "drama memory tender aching"],
  ["Decision to Leave", 2022, "thriller romance elegant twisty"],
  ["RRR", 2022, "action epic exuberant spectacle"],
  ["Top Gun: Maverick", 2022, "action drama rousing slick"],
  ["The Whale", 2022, "drama intimate raw moving"],
  ["Nope", 2022, "horror sci-fi spectacle eerie"],
  ["The Fabelmans", 2022, "drama coming-of-age nostalgic tender"],
  ["Triangle of Sadness", 2022, "comedy satire biting absurd"],
  ["Oppenheimer", 2023, "drama biopic epic propulsive"],
  ["Poor Things", 2023, "comedy fantasy surreal vibrant"],
  ["Past Lives", 2023, "romance drama tender wistful"],
  ["Killers of the Flower Moon", 2023, "crime drama epic somber"],
  ["The Zone of Interest", 2023, "drama war austere chilling"],
  ["Anatomy of a Fall", 2023, "drama thriller cerebral tense"],
  ["The Holdovers", 2023, "comedy drama warm melancholic"],
  ["Spider-Man: Across the Spider-Verse", 2023, "animation action vibrant inventive"],
  ["Barbie", 2023, "comedy fantasy satire vibrant"],
  ["Perfect Days", 2023, "drama contemplative gentle serene"],
  ["The Boy and the Heron", 2023, "animation fantasy dreamlike enigmatic"],
  ["Godzilla Minus One", 2023, "action drama monster stirring"],
  ["Dune: Part Two", 2024, "sci-fi epic adventure immersive"],
  ["The Substance", 2024, "horror satire body lurid"],
  ["Challengers", 2024, "drama romance sports kinetic"],
  ["Anora", 2024, "comedy drama frenetic tender"],
  ["The Brutalist", 2024, "drama epic ambitious austere"],
  ["Nosferatu", 2024, "horror gothic dread lush"],
  ["A Real Pain", 2024, "comedy drama melancholic tender"],
  ["Conclave", 2024, "thriller drama tense stately"],
  ["Flow", 2024, "animation adventure wordless luminous"],

  // --- Horror across the decades ---
  ["The Cabinet of Dr. Caligari", 1920, "horror silent expressionist surreal"],
  ["Nosferatu", 1922, "horror silent gothic eerie"],
  ["Freaks", 1932, "horror drama unsettling humane"],
  ["Cat People", 1942, "horror noir suggestive eerie"],
  ["Les Diaboliques", 1955, "thriller horror twist suspenseful"],
  ["Eyes Without a Face", 1960, "horror poetic eerie melancholic"],
  ["The Haunting", 1963, "horror supernatural atmospheric dread"],
  ["Kwaidan", 1964, "horror anthology painterly eerie"],
  ["The Wicker Man", 1973, "horror folk eerie unsettling"],
  ["Black Christmas", 1974, "horror slasher proto chilling"],
  ["Phantasm", 1979, "horror surreal dreamlike cult"],
  ["The Changeling", 1980, "horror supernatural restrained eerie"],
  ["The Entity", 1982, "horror supernatural disturbing relentless"],
  ["Christine", 1983, "horror supernatural sinister stylish"],
  ["Re-Animator", 1985, "horror comedy gory frantic"],
  ["The Lost Boys", 1987, "horror comedy vampire stylish"],
  ["Hellraiser", 1987, "horror supernatural grisly baroque"],
  ["Tetsuo: The Iron Man", 1989, "horror sci-fi body frenetic"],
  ["Jacob's Ladder", 1990, "horror psychological nightmarish harrowing"],
  ["Candyman", 1992, "horror supernatural urban eerie"],
  ["Cronos", 1993, "horror fantasy tender macabre"],
  ["The Devil's Backbone", 2001, "horror drama gothic mournful"],
  ["The Descent", 2005, "horror survival claustrophobic visceral"],
  ["The Orphanage", 2007, "horror drama gothic mournful"],
  ["Trick 'r Treat", 2007, "horror anthology playful macabre"],
  ["Martyrs", 2008, "horror brutal harrowing extreme"],
  ["The House of the Devil", 2009, "horror slow-burn atmospheric retro"],
  ["Insidious", 2010, "horror supernatural dread jolting"],
  ["Kill List", 2011, "horror thriller dread unsettling"],
  ["The Conjuring", 2013, "horror supernatural dread crafted"],
  ["The Wailing", 2016, "horror mystery dread sprawling"],
  ["Train to Busan", 2016, "horror action zombie emotional"],
  ["A Quiet Place", 2018, "horror thriller tense inventive"],
  ["Suspiria", 2018, "horror drama lurid haunting"],
  ["Climax", 2018, "horror drama hypnotic nightmarish"],
  ["Us", 2019, "horror thriller allegory unsettling"],
  ["The Vast of Night", 2019, "sci-fi mystery atmospheric retro"],
  ["His House", 2020, "horror drama haunting poignant"],
  ["Saint Maud", 2020, "horror drama austere unsettling"],
  ["Censor", 2021, "horror psychological retro eerie"],
  ["X", 2022, "horror slasher retro lurid"],
  ["Pearl", 2022, "horror drama lurid vivid"],
  ["Talk to Me", 2022, "horror supernatural visceral dread"],
  ["Skinamarink", 2022, "horror experimental dread minimalist"],
  ["Smile", 2022, "horror supernatural dread jolting"],
  ["Longlegs", 2024, "horror thriller eerie procedural"],
  ["I Saw the TV Glow", 2024, "horror drama dreamlike haunting"],
  ["Late Night with the Devil", 2023, "horror retro inventive eerie"],

  // --- Science fiction beyond the canon ---
  ["Forbidden Planet", 1956, "sci-fi adventure classic imaginative"],
  ["Fantastic Voyage", 1966, "sci-fi adventure inventive retro"],
  ["Silent Running", 1972, "sci-fi drama melancholic environmental"],
  ["Soylent Green", 1973, "sci-fi dystopian grim allegorical"],
  ["Westworld", 1973, "sci-fi thriller prophetic tense"],
  ["The Man Who Fell to Earth", 1976, "sci-fi drama alien melancholic"],
  ["Tron", 1982, "sci-fi adventure digital pioneering"],
  ["The Quiet Earth", 1985, "sci-fi drama desolate eerie"],
  ["The Abyss", 1989, "sci-fi adventure immersive wondrous"],
  ["Cube", 1997, "sci-fi thriller claustrophobic paranoid"],
  ["eXistenZ", 1999, "sci-fi thriller body cerebral"],
  ["Primer", 2004, "sci-fi thriller cerebral lo-fi"],
  ["Sunshine", 2007, "sci-fi thriller awe dread"],
  ["Timecrimes", 2007, "sci-fi thriller twisty lean"],
  ["Source Code", 2011, "sci-fi thriller inventive propulsive"],
  ["Upstream Color", 2013, "sci-fi drama elliptical hypnotic"],
  ["Coherence", 2013, "sci-fi thriller cerebral lo-fi"],
  ["Edge of Tomorrow", 2014, "sci-fi action inventive propulsive"],
  ["Predestination", 2014, "sci-fi thriller twisty cerebral"],
  ["The Martian", 2015, "sci-fi adventure resourceful uplifting"],
  ["Midnight Special", 2016, "sci-fi drama tender mysterious"],
  ["Prospect", 2018, "sci-fi western gritty atmospheric"],
  ["High Life", 2018, "sci-fi drama austere unsettling"],
  ["Aniara", 2018, "sci-fi drama bleak elegiac"],
  ["Color Out of Space", 2019, "sci-fi horror cosmic lurid"],
  ["After Yang", 2021, "sci-fi drama tender meditative"],

  // --- Japanese cinema & anime ---
  ["Ugetsu", 1953, "drama ghost poetic haunting"],
  ["Sansho the Bailiff", 1954, "drama tragedy poetic devastating"],
  ["Floating Weeds", 1959, "drama family quiet poignant"],
  ["The Hidden Fortress", 1958, "adventure samurai rousing spirited"],
  ["High and Low", 1963, "crime thriller moral taut"],
  ["Woman in the Dunes", 1964, "drama surreal hypnotic existential"],
  ["Kuroneko", 1968, "horror folk eerie elegant"],
  ["The Castle of Cagliostro", 1979, "animation adventure caper spirited"],
  ["Nausicaä of the Valley of the Wind", 1984, "animation fantasy epic environmental"],
  ["Castle in the Sky", 1986, "animation adventure wondrous sweeping"],
  ["Kiki's Delivery Service", 1989, "animation family gentle whimsical"],
  ["Only Yesterday", 1991, "animation drama nostalgic tender"],
  ["Porco Rosso", 1992, "animation adventure wistful charming"],
  ["Ghost in the Shell", 1995, "animation sci-fi cerebral atmospheric"],
  ["Perfect Blue", 1997, "animation thriller psychological unsettling"],
  ["Princess Mononoke", 1997, "animation fantasy epic environmental"],
  ["After Life", 1998, "drama fantasy tender contemplative"],
  ["Audition", 1999, "horror thriller slow-burn disturbing"],
  ["Millennium Actress", 2001, "animation drama dreamy poignant"],
  ["Pulse", 2001, "horror supernatural dread melancholic"],
  ["Tokyo Godfathers", 2003, "animation comedy warm humane"],
  ["Howl's Moving Castle", 2004, "animation fantasy whimsical enchanting"],
  ["Paprika", 2006, "animation sci-fi surreal kaleidoscopic"],
  ["Departures", 2008, "drama tender humane bittersweet"],
  ["Ponyo", 2008, "animation family wondrous gentle"],
  ["I Wish", 2011, "drama family tender gentle"],
  ["The Wind Rises", 2013, "animation drama bittersweet sweeping"],
  ["The Tale of the Princess Kaguya", 2013, "animation fantasy painterly poignant"],
  ["A Silent Voice", 2016, "animation drama tender redemptive"],
  ["Shoplifters", 2018, "drama family tender melancholic"],
  ["Weathering with You", 2019, "animation romance luminous yearning"],

  // --- Korean cinema ---
  ["The Housemaid", 1960, "thriller drama lurid claustrophobic"],
  ["Sympathy for Mr. Vengeance", 2002, "thriller crime brutal bleak"],
  ["A Tale of Two Sisters", 2003, "horror drama gothic twisty"],
  ["The Host", 2006, "monster comedy satire heartfelt"],
  ["I Saw the Devil", 2010, "thriller horror brutal relentless"],
  ["Poetry", 2010, "drama tender contemplative moving"],
  ["The Yellow Sea", 2010, "thriller action visceral sprawling"],
  ["Mother", 2009, "thriller drama tense aching"],
  ["Snowpiercer", 2013, "sci-fi action dystopian allegorical"],
  ["The Wailing", 2016, "horror mystery dread sprawling"],
  ["Burning", 2018, "thriller drama slow-burn enigmatic"],
  ["The Handmaiden", 2016, "thriller romance lush twisty"],
  ["Train to Busan", 2016, "horror action zombie emotional"],
  ["Parasite", 2019, "thriller drama satire sharp"],
  ["Decision to Leave", 2022, "thriller romance elegant twisty"],
  ["Oldboy", 2003, "thriller crime violent operatic"],

  // --- French, Italian & European arthouse ---
  ["The Rules of the Game", 1939, "comedy drama satire bittersweet"],
  ["Children of Paradise", 1945, "romance drama epic poetic"],
  ["Beauty and the Beast", 1946, "fantasy romance poetic dreamlike"],
  ["Diary of a Country Priest", 1951, "drama austere spiritual quiet"],
  ["Mr. Hulot's Holiday", 1953, "comedy gentle whimsical observational"],
  ["Les Vampires", 1915, "crime serial pulp inventive"],
  ["Pickpocket", 1959, "crime drama austere spare"],
  ["L'Avventura", 1960, "drama mystery enigmatic austere"],
  ["Jules and Jim", 1962, "romance drama buoyant bittersweet"],
  ["Cléo from 5 to 7", 1962, "drama intimate observant tender"],
  ["The Leopard", 1963, "drama historical epic elegiac"],
  ["Contempt", 1963, "drama romance stylish melancholic"],
  ["The Umbrellas of Cherbourg", 1964, "musical romance bittersweet vibrant"],
  ["Pierrot le Fou", 1965, "crime romance playful anarchic"],
  ["Au Hasard Balthazar", 1966, "drama allegory austere moving"],
  ["Belle de Jour", 1967, "drama surreal enigmatic chic"],
  ["Playtime", 1967, "comedy satire intricate observational"],
  ["The Conformist", 1970, "drama political stylish chilling"],
  ["The Discreet Charm of the Bourgeoisie", 1972, "comedy surreal satirical sly"],
  ["Cries and Whispers", 1972, "drama intimate harrowing painterly"],
  ["Amarcord", 1973, "comedy drama nostalgic warm"],
  ["The Spirit of the Beehive", 1973, "drama coming-of-age dreamlike haunting"],
  ["The Mother and the Whore", 1973, "drama talky raw intimate"],
  ["The Passenger", 1975, "drama mystery enigmatic meditative"],
  ["1900", 1976, "drama historical epic sprawling"],
  ["The American Friend", 1977, "thriller noir moody enigmatic"],
  ["The Marriage of Maria Braun", 1979, "drama historical sardonic resonant"],
  ["Diva", 1981, "thriller romance stylish kinetic"],
  ["Three Colors: Blue", 1993, "drama grief luminous contemplative"],
  ["La Haine", 1995, "drama social urgent kinetic"],
  ["The Dreamers", 2003, "drama romance sensual nostalgic"],
  ["A Christmas Tale", 2008, "drama family caustic warm"],
  ["The Skin I Live In", 2011, "thriller horror lush twisty"],
  ["Blue Is the Warmest Color", 2013, "romance drama raw intimate"],
  ["The Great Beauty", 2013, "drama satire lavish elegiac"],
  ["Mustang", 2015, "drama coming-of-age vibrant defiant"],
  ["Happy as Lazzaro", 2018, "drama fable lyrical poignant"],
  ["Portrait of a Lady on Fire", 2019, "romance drama luminous restrained"],

  // --- Westerns ---
  ["My Darling Clementine", 1946, "western drama elegiac classic"],
  ["Red River", 1948, "western drama epic rugged"],
  ["Winchester '73", 1950, "western drama taut classic"],
  ["Shane", 1953, "western drama mythic poignant"],
  ["Johnny Guitar", 1954, "western drama operatic stylized"],
  ["The Man Who Shot Liberty Valance", 1962, "western drama elegiac moral"],
  ["Once Upon a Time in the West", 1968, "western epic operatic elegiac"],
  ["McCabe & Mrs. Miller", 1971, "western drama melancholic revisionist"],
  ["Pat Garrett and Billy the Kid", 1973, "western drama elegiac ragged"],
  ["The Proposition", 2005, "western drama brutal poetic"],
  ["3:10 to Yuma", 2007, "western drama tense moral"],
  ["Meek's Cutoff", 2010, "western drama austere meditative"],
  ["Bone Tomahawk", 2015, "western horror brutal grim"],
  ["The Sisters Brothers", 2018, "western comedy melancholic offbeat"],
  ["The Ballad of Buster Scruggs", 2018, "western anthology wry macabre"],
  ["News of the World", 2020, "western drama gentle rugged"],

  // --- Animation (Western studios) ---
  ["Pinocchio", 1940, "animation fantasy fable wondrous"],
  ["Dumbo", 1941, "animation family tender bittersweet"],
  ["Bambi", 1942, "animation family tender poignant"],
  ["Cinderella", 1950, "animation fairytale musical wholesome"],
  ["Sleeping Beauty", 1959, "animation fairytale lush classic"],
  ["101 Dalmatians", 1961, "animation family playful charming"],
  ["The Jungle Book", 1967, "animation musical family breezy"],
  ["Watership Down", 1978, "animation adventure harrowing lyrical"],
  ["The Secret of NIMH", 1982, "animation fantasy dark adventurous"],
  ["The Land Before Time", 1988, "animation adventure tender poignant"],
  ["The Little Mermaid", 1989, "animation musical romance vibrant"],
  ["Aladdin", 1992, "animation musical adventure exuberant"],
  ["The Lion King", 1994, "animation musical epic emotional"],
  ["Toy Story", 1995, "animation family adventure heartfelt"],
  ["The Iron Giant", 1999, "animation sci-fi family heartfelt"],
  ["Shrek", 2001, "animation comedy fairytale subversive"],
  ["Lilo & Stitch", 2002, "animation family heartfelt offbeat"],
  ["Finding Nemo", 2003, "animation family adventure heartfelt"],
  ["The Incredibles", 2004, "animation action family witty"],
  ["Wallace & Gromit: The Curse of the Were-Rabbit", 2005, "animation comedy whimsical inventive"],
  ["Ratatouille", 2007, "animation family comedy heartfelt"],
  ["WALL-E", 2008, "animation sci-fi tender wondrous"],
  ["How to Train Your Dragon", 2010, "animation adventure family rousing"],
  ["Rango", 2011, "animation western comedy offbeat"],
  ["The Lego Movie", 2014, "animation comedy inventive exuberant"],
  ["Zootopia", 2016, "animation comedy allegory clever"],
  ["Klaus", 2019, "animation family heartfelt charming"],
  ["Wolfwalkers", 2020, "animation fantasy lyrical luminous"],
  ["The Mitchells vs. the Machines", 2021, "animation comedy frenetic heartfelt"],
  ["Puss in Boots: The Last Wish", 2022, "animation adventure vibrant heartfelt"],

  // --- Comedy ---
  ["Duck Soup", 1933, "comedy satire anarchic classic"],
  ["His Girl Friday", 1940, "comedy screwball rapid witty"],
  ["The Lady Eve", 1941, "comedy romance screwball sparkling"],
  ["Arsenic and Old Lace", 1944, "comedy macabre frantic playful"],
  ["The Ladykillers", 1955, "comedy crime droll macabre"],
  ["The Party", 1968, "comedy slapstick chaotic gentle"],
  ["The Producers", 1967, "comedy satire farce outrageous"],
  ["Sleeper", 1973, "comedy sci-fi satire playful"],
  ["The Jerk", 1979, "comedy absurd gentle silly"],
  ["Caddyshack", 1980, "comedy sports anarchic raunchy"],
  ["Trading Places", 1983, "comedy satire sharp warm"],
  ["This Is Spinal Tap", 1984, "comedy mockumentary music deadpan"],
  ["Planes, Trains and Automobiles", 1987, "comedy road warm humane"],
  ["Coming to America", 1988, "comedy romance warm vibrant"],
  ["Groundhog Day", 1993, "comedy fantasy romance philosophical"],
  ["Dumb and Dumber", 1994, "comedy road absurd silly"],
  ["The Big Lebowski", 1998, "comedy crime shaggy cult"],
  ["Rushmore", 1998, "comedy drama quirky bittersweet"],
  ["Best in Show", 2000, "comedy mockumentary droll affectionate"],
  ["Zoolander", 2001, "comedy satire absurd silly"],
  ["Anchorman", 2004, "comedy absurd quotable goofy"],
  ["Napoleon Dynamite", 2004, "comedy deadpan quirky offbeat"],
  ["Hot Fuzz", 2007, "comedy action parody clever"],
  ["Superbad", 2007, "comedy coming-of-age raunchy warm"],
  ["In the Loop", 2009, "comedy satire political acerbic"],
  ["Bridesmaids", 2011, "comedy raunchy warm humane"],
  ["What We Do in the Shadows", 2014, "comedy horror mockumentary droll"],
  ["The Nice Guys", 2016, "comedy crime breezy stylish"],
  ["Game Night", 2018, "comedy thriller twisty playful"],
  ["Booksmart", 2019, "comedy coming-of-age warm witty"],
  ["Palm Springs", 2020, "comedy romance sci-fi inventive"],

  // --- Action & thrillers ---
  ["The 39 Steps", 1935, "thriller espionage breezy clever"],
  ["The Wages of Fear", 1953, "thriller survival tense grueling"],
  ["The Killing", 1956, "noir crime heist taut"],
  ["Goldfinger", 1964, "action espionage slick iconic"],
  ["Point Blank", 1967, "crime thriller stylish cold"],
  ["Bullitt", 1968, "crime thriller cool kinetic"],
  ["The Italian Job", 1969, "crime caper breezy stylish"],
  ["The French Connection", 1971, "crime thriller gritty kinetic"],
  ["The Day of the Jackal", 1973, "thriller procedural taut methodical"],
  ["Three Days of the Condor", 1975, "thriller espionage paranoid sleek"],
  ["Marathon Man", 1976, "thriller paranoid tense relentless"],
  ["The Driver", 1978, "crime thriller minimalist cool"],
  ["Escape from New York", 1981, "action sci-fi gritty cult"],
  ["The Road Warrior", 1981, "action sci-fi dystopian visceral"],
  ["Lethal Weapon", 1987, "action buddy kinetic gritty"],
  ["Speed", 1994, "action thriller propulsive lean"],
  ["The Rock", 1996, "action thriller bombastic slick"],
  ["Face/Off", 1997, "action thriller operatic kinetic"],
  ["Ronin", 1998, "thriller action methodical sleek"],
  ["The Bourne Identity", 2002, "action thriller propulsive grounded"],
  ["The Raid", 2011, "action martial-arts relentless visceral"],
  ["Skyfall", 2012, "action espionage stylish elegiac"],
  ["John Wick", 2014, "action thriller stylish kinetic"],
  ["Mission: Impossible – Fallout", 2018, "action thriller propulsive slick"],
  ["Extraction", 2020, "action thriller visceral propulsive"],
  ["The Night Comes for Us", 2018, "action crime brutal relentless"],

  // --- Crime & noir ---
  ["Scarface", 1932, "crime drama gritty classic"],
  ["White Heat", 1949, "crime noir explosive iconic"],
  ["Gun Crazy", 1950, "noir crime romance feverish"],
  ["The Asphalt Jungle", 1950, "noir crime heist fatalistic"],
  ["Kiss Me Deadly", 1955, "noir crime apocalyptic feverish"],
  ["Rififi", 1955, "noir crime heist meticulous"],
  ["Sweet Smell of Success", 1957, "noir drama cynical glittering"],
  ["Branded to Kill", 1967, "crime noir surreal stylized"],
  ["The Long Goodbye", 1973, "noir crime laidback sardonic"],
  ["The Friends of Eddie Coyle", 1973, "crime drama bleak understated"],
  ["Thief", 1981, "crime drama stylish moody"],
  ["To Live and Die in L.A.", 1985, "crime thriller stylish nihilistic"],
  ["State of Grace", 1990, "crime drama tense tragic"],
  ["King of New York", 1990, "crime drama stylish operatic"],
  ["Romeo Is Bleeding", 1993, "noir crime lurid feverish"],
  ["The Usual Suspects", 1995, "crime thriller twist clever"],
  ["Donnie Brasco", 1997, "crime drama tense poignant"],
  ["A History of Violence", 2005, "thriller crime tense restrained"],
  ["Gone Girl", 2014, "thriller mystery twisty caustic"],
  ["A Most Wanted Man", 2014, "thriller espionage understated tense"],
  ["Wind River", 2017, "crime drama bleak tense"],
  ["The Drop", 2014, "crime drama understated tense"],

  // --- Romance & musicals ---
  ["Top Hat", 1935, "musical romance elegant breezy"],
  ["An American in Paris", 1951, "musical romance lavish vibrant"],
  ["Gigi", 1958, "musical romance charming lavish"],
  ["A Hard Day's Night", 1964, "musical comedy buoyant kinetic"],
  ["Funny Girl", 1968, "musical drama buoyant bittersweet"],
  ["Cabaret", 1972, "musical drama decadent unsettling"],
  ["Nashville", 1975, "musical drama sprawling satirical"],
  ["All That Jazz", 1979, "musical drama frenetic introspective"],
  ["Dirty Dancing", 1987, "romance musical nostalgic warm"],
  ["Moulin Rouge!", 2001, "musical romance frenetic lush"],
  ["Chicago", 2002, "musical crime razzle satirical"],
  ["Once", 2007, "romance music intimate tender"],
  ["Brooklyn", 2015, "romance drama tender luminous"],
  ["Sing Street", 2016, "musical coming-of-age buoyant warm"],
  ["A Star Is Born", 2018, "musical romance raw soaring"],
  ["Eternal Sunshine of the Spotless Mind", 2004, "romance sci-fi melancholic inventive"],
  ["500 Days of Summer", 2009, "romance comedy bittersweet stylish"],
  ["Like Crazy", 2011, "romance drama aching intimate"],
  ["The Big Sick", 2017, "romance comedy warm humane"],

  // --- Indian, Latin American, and other world cinema ---
  ["Pather Panchali", 1955, "drama poetic tender humane"],
  ["The Music Room", 1958, "drama elegiac decadent austere"],
  ["Mother India", 1957, "drama epic melodrama sweeping"],
  ["Sholay", 1975, "action adventure epic iconic"],
  ["Salaam Bombay!", 1988, "drama social gritty humane"],
  ["Dilwale Dulhania Le Jayenge", 1995, "romance musical sweeping warm"],
  ["Lagaan", 2001, "drama sports musical rousing"],
  ["Black Friday", 2004, "crime drama sprawling tense"],
  ["3 Idiots", 2009, "comedy drama warm uplifting"],
  ["The Lunchbox", 2013, "romance drama tender gentle"],
  ["Gangs of Wasseypur", 2012, "crime drama epic sprawling"],
  ["Tumbbad", 2018, "horror fantasy lush mythic"],
  ["Los Olvidados", 1950, "drama neorealist harrowing unflinching"],
  ["Black Orpheus", 1959, "romance musical vibrant tragic"],
  ["Memories of Underdevelopment", 1968, "drama political reflective wry"],
  ["The Official Story", 1985, "drama political harrowing humane"],
  ["Central Station", 1998, "drama road tender humane"],
  ["The Motorcycle Diaries", 2004, "drama road searching tender"],
  ["The Secret in Their Eyes", 2009, "thriller romance crime haunting"],
  ["Wild Tales", 2014, "comedy anthology savage exhilarating"],
  ["Embrace of the Serpent", 2015, "drama adventure hypnotic mythic"],
  ["A Separation", 2011, "drama tense moral humane"],
  ["The Salesman", 2016, "drama tense moral restrained"],
  ["Capernaum", 2018, "drama social harrowing humane"],
  ["Atlantics", 2019, "drama romance haunting lyrical"],
  ["Timbuktu", 2014, "drama political tender sorrowful"],

  // --- Documentaries & docu-adjacent ---
  ["Nanook of the North", 1922, "documentary silent pioneering observational"],
  ["Night and Fog", 1956, "documentary war harrowing essential"],
  ["Grey Gardens", 1975, "documentary intimate eccentric haunting"],
  ["Koyaanisqatsi", 1982, "documentary experimental hypnotic wordless"],
  ["Shoah", 1985, "documentary war epic devastating"],
  ["Hoop Dreams", 1994, "documentary sports sprawling moving"],
  ["Crumb", 1994, "documentary biography raw unsettling"],
  ["Grizzly Man", 2005, "documentary nature haunting strange"],
  ["The Act of Killing", 2012, "documentary political surreal harrowing"],
  ["Stories We Tell", 2012, "documentary memoir intimate inventive"],
  ["Leviathan", 2012, "documentary experimental immersive visceral"],
  ["O.J.: Made in America", 2016, "documentary epic sprawling incisive"],
  ["Honeyland", 2019, "documentary observational lyrical tender"],

  // --- Cult, midnight & genre oddities ---
  ["Freaks", 1932, "horror cult unsettling humane"],
  ["El Topo", 1970, "western surreal mystical violent"],
  ["The Holy Mountain", 1973, "drama surreal psychedelic provocative"],
  ["The Wicker Man", 1973, "horror folk eerie unsettling"],
  ["Phantom of the Paradise", 1974, "musical horror satire flamboyant"],
  ["Mad God", 2021, "animation horror surreal nightmarish"],
  ["Liquid Sky", 1982, "sci-fi cult lurid strange"],
  ["Repo Man", 1984, "sci-fi comedy punk offbeat"],
  ["Brazil", 1985, "sci-fi comedy dystopian surreal"],
  ["Big Trouble in Little China", 1986, "action comedy fantasy campy"],
  ["The Adventures of Buckaroo Banzai", 1984, "sci-fi comedy zany cult"],
  ["Tampopo", 1985, "comedy food whimsical playful"],
  ["The City of Lost Children", 1995, "fantasy sci-fi steampunk whimsical"],
  ["Tetsuo II: Body Hammer", 1992, "horror sci-fi body frenetic"],
  ["A Field in England", 2013, "drama horror hallucinatory austere"],
  ["The Lure", 2015, "musical horror surreal lurid"],
  ["The Love Witch", 2016, "horror romance retro stylized"],
  ["Swiss Army Man", 2016, "comedy drama absurd tender"],
  ["Mandy", 2018, "horror action psychedelic vengeful"],

  // --- More widely-loved staples across eras ---
  ["Yankee Doodle Dandy", 1942, "musical biopic rousing patriotic"],
  ["The Best Years of Our Lives", 1946, "drama postwar humane moving"],
  ["A Place in the Sun", 1951, "drama romance tragic lush"],
  ["Roman Holiday", 1953, "romance comedy charming bittersweet"],
  ["The Bridge on the River Kwai", 1957, "war drama epic moral"],
  ["Anatomy of a Murder", 1959, "drama courtroom sharp absorbing"],
  ["Judgment at Nuremberg", 1961, "drama courtroom historical weighty"],
  ["The Hustler", 1961, "drama sports gritty intense"],
  ["A Man for All Seasons", 1966, "drama historical principled stately"],
  ["In the Heat of the Night", 1967, "drama crime tense moral"],
  ["The Lion in Winter", 1968, "drama historical sharp theatrical"],
  ["Patton", 1970, "war biopic epic commanding"],
  ["Klute", 1971, "thriller drama paranoid moody"],
  ["Serpico", 1973, "crime drama gritty principled"],
  ["The Parallax View", 1974, "thriller political paranoid chilling"],
  ["All the President's Men", 1976, "drama procedural taut absorbing"],
  ["Kramer vs. Kramer", 1979, "drama family tender wrenching"],
  ["Gandhi", 1982, "biopic epic historical stirring"],
  ["The Right Stuff", 1983, "drama historical epic rousing"],
  ["Witness", 1985, "thriller romance restrained tender"],
  ["The Color Purple", 1985, "drama epic moving sweeping"],
  ["Stand and Deliver", 1988, "drama inspirational earnest warm"],
  ["Awakenings", 1990, "drama medical tender poignant"],
  ["A League of Their Own", 1992, "comedy drama sports warm"],
  ["Philadelphia", 1993, "drama courtroom moving principled"],
  ["Apollo 13", 1995, "drama historical tense rousing"],
  ["Dead Man Walking", 1995, "drama moral harrowing humane"],
  ["Good Will Hunting", 1997, "drama coming-of-age heartfelt earnest"],
  ["The Insider", 1999, "drama procedural tense principled"],
  ["Erin Brockovich", 2000, "drama legal spirited warm"],
  ["A Beautiful Mind", 2001, "drama biopic moving sweeping"],
  ["Cast Away", 2000, "drama survival intimate harrowing"],
  ["Million Dollar Baby", 2004, "drama sports somber moving"],
  ["Walk the Line", 2005, "musical biopic warm soulful"],
  ["The Pursuit of Happyness", 2006, "drama uplifting earnest tender"],
  ["Michael Clayton", 2007, "thriller drama corporate taut"],
  ["The Blind Side", 2009, "drama sports uplifting warm"],
  ["The Fighter", 2010, "drama sports gritty rousing"],
  ["Moneyball", 2011, "drama sports cerebral wry"],
  ["Argo", 2012, "thriller historical tense slick"],
  ["Captain Phillips", 2013, "thriller survival tense visceral"],
  ["The Imitation Game", 2014, "drama biopic historical poignant"],
  ["Bridge of Spies", 2015, "drama espionage stately principled"],
  ["Hidden Figures", 2016, "drama historical uplifting warm"],
  ["Darkest Hour", 2017, "drama historical stirring intimate"],
  ["Green Book", 2018, "drama road warm crowd-pleasing"],
  ["Ford v Ferrari", 2019, "drama sports rousing slick"],
  ["The Trial of the Chicago 7", 2020, "drama courtroom historical sharp"],
  ["King Richard", 2021, "drama sports earnest warm"],
];
